--- Generated by h-lua(https://github.com/h-lua/h-lua)

-- h-lua库
require "h-lua"
-- alias h-lua库别称（参考）
require "scripts.alias"
-- setup
require "scripts.setup"
-- start 游戏主程（必备main函数）
require "scripts.start"